version: '3.3'

volumes:
  mongodb_volume:

services:
  app:
    build: ./app
    restart: always
    env_file:
      - .env
    expose:
      - 8080
    depends_on:
      - mongodb
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 80:80
    depends_on:
      - app
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb_volume:/data/db
    restart: always